/**
 * Instructions to Add Sample Data to Your MongoDB Database
 */

console.log('╔════════════════════════════════════════════════════════════════╗');
console.log('║                                                                ║');
console.log('║     🍃  YOUR MONGODB DATABASE IS EMPTY!                        ║');
console.log('║                                                                ║');
console.log('╚════════════════════════════════════════════════════════════════╝');
console.log('');
console.log('This is why Schema Explorer shows "No collections match your search."');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('📋 SOLUTION: Add Some Data to Your MongoDB Database');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('🔧 Method 1: Using MongoDB Shell (if local MongoDB)');
console.log('');
console.log('   1. Open PowerShell/Terminal');
console.log('   2. Run: mongo MONGODB_test');
console.log('   3. Paste these commands:');
console.log('');
console.log('      db.users.insertMany([');
console.log('        { name: "Alice", age: 30, role: "admin", email: "alice@example.com" },');
console.log('        { name: "Bob", age: 25, role: "user", email: "bob@example.com" },');
console.log('        { name: "Charlie", age: 35, role: "moderator", email: "charlie@example.com" }');
console.log('      ])');
console.log('');
console.log('      db.products.insertMany([');
console.log('        { name: "Laptop", price: 999.99, category: "Electronics", stock: 50 },');
console.log('        { name: "Mouse", price: 29.99, category: "Accessories", stock: 200 },');
console.log('        { name: "Keyboard", price: 79.99, category: "Accessories", stock: 150 }');
console.log('      ])');
console.log('');
console.log('      db.orders.insertMany([');
console.log('        { orderId: "ORD001", userId: 1, total: 999.99, status: "completed" },');
console.log('        { orderId: "ORD002", userId: 2, total: 29.99, status: "pending" }');
console.log('      ])');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('🌐 Method 2: Using MongoDB Atlas (if cloud MongoDB)');
console.log('');
console.log('   1. Go to https://cloud.mongodb.com');
console.log('   2. Login to your account');
console.log('   3. Select your cluster');
console.log('   4. Click "Collections"');
console.log('   5. Click "Create Database"');
console.log('      - Database name: MONGODB_test');
console.log('      - Collection name: users');
console.log('   6. Click "Insert Document" and add:');
console.log('      { "name": "Alice", "age": 30, "role": "admin" }');
console.log('   7. Repeat to create more collections and documents');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('🐍 Method 3: Using MongoDB Compass (GUI Tool)');
console.log('');
console.log('   1. Download: https://www.mongodb.com/products/compass');
console.log('   2. Connect using your connection string');
console.log('   3. Create database "MONGODB_test"');
console.log('   4. Create collections: users, products, orders');
console.log('   5. Add documents using the GUI');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('✅ AFTER ADDING DATA:');
console.log('');
console.log('   1. Go back to DevQuery: http://localhost:5173');
console.log('   2. Click "Refresh Schema" button');
console.log('   3. Your collections will appear! 🎉');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('❓ TROUBLESHOOTING:');
console.log('');
console.log('   Q: Still no collections showing?');
console.log('   A: Check browser console (F12) for errors');
console.log('');
console.log('   Q: MongoDB not running?');
console.log('   A: Start it with: mongod');
console.log('');
console.log('   Q: Using MongoDB Atlas?');
console.log('   A: Make sure your IP is whitelisted in Atlas');
console.log('');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
